INSERT INTO Account (username, firstname, lastname, email, password, status, securityQuestion, securityAnswer) VALUES
('john_doe', 'John', 'Doe', 'john.doe@hotmail.com', 'password123', 1, 'What is your favorite color?', 'Blue'),
('jane_smith', 'Jane', 'Smith', 'jane.smith@gmail.com', 'securepass', 0, 'What was the name of your first pet?', 'Fluffy'),
('alex_brown', 'Alex', 'Brown', 'alex.brown@yahoo.com', 'mypassword', 1, 'What is your mother\'s maiden name?', 'Williams'),
('lucy_jones', 'Lucy', 'Jones', 'lucy.jones@gmail.com', 'mypassword1', 0, 'What is your birthplace?', 'New York'),
('michael_taylor', 'Michael', 'Taylor', 'michael.taylor@hotmail.com', 'securepass1', 1, 'What is your favorite book?', '1984'),
('emma_wilson', 'Emma', 'Wilson', 'emma.wilson@yahoo.com', '123password', 0, 'What is your father\'s middle name?', 'James'),
('liam_moore', 'Liam', 'Moore', 'liam.moore@gmail.com', 'bestpass', 1, 'What was the name of your first school?', 'Riverdale'),
('sophia_king', 'Sophia', 'King', 'sophia.king@hotmail.com', 'safepassword', 0, 'What is the name of your childhood friend?', 'Emily'),
('jack_hill', 'Jack', 'Hill', 'jack.hill@gmail.com', 'mypassword123', 1, 'What is your favorite vacation destination?', 'Hawaii'),
('olivia_scott', 'Olivia', 'Scott', 'olivia.scott@yahoo.com', 'strongpass', 0, 'What is your favorite food?', 'Pizza'),
('noah_clark', 'Noah', 'Clark', 'noah.clark@gmail.com', 'mypassword4', 1, 'What is your favorite movie?', 'Inception'),
('mary_williams', 'Mary', 'Williams', 'mary.williams@aol.com', 'password5', 0, 'What is your favorite animal?', 'Dog'),
('david_johnson', 'David', 'Johnson', 'david.johnson@outlook.com', 'mypassword6', 1, 'What was the name of your first car?', 'Toyota'),
('lisa_martin', 'Lisa', 'Martin', 'lisa.martin@icloud.com', 'mypassword7', 0, 'What was your first job?', 'Barista'),
('james_white', 'James', 'White', 'james.white@protonmail.com', 'password8', 1, 'What is your favorite sport?', 'Basketball'),
('olga_smith', 'Olga', 'Smith', 'olga.smith@aol.com', 'mypassword9', 0, 'What is your favorite hobby?', 'Painting'),
('william_jones', 'William', 'Jones', 'william.jones@googlemail.com', 'securepass10', 1, 'What is the name of your favorite teacher?', 'Mrs. Taylor'),
('austin_lee', 'Austin', 'Lee', 'austin.lee@outlook.com', 'bestpassword', 0, 'What is the name of the street you grew up on?', 'Elm Street'),
('lucas_garcia', 'Lucas', 'Garcia', 'lucas.garcia@icloud.com', 'pass12345', 1, 'What is your favorite season?', 'Summer');


-- Recipe table
INSERT INTO Recipe (title, description, category, difficulty, prepTime, servings, status) VALUES
('Spaghetti Bolognese', 'A classic Italian pasta dish with rich meat sauce.', 'Meal', 'Medium', 30.0, 4, 1),
('Vegetable Stir Fry', 'A quick and healthy mix of fresh vegetables and soy sauce.', 'Meal', 'Easy', 20.0, 2, 1),
('Chocolate Cake', 'A moist and rich chocolate cake perfect for dessert.', 'Dessert', 'Hard', 60.0, 8, 1),
('Chicken Curry', 'A spicy and flavorful chicken curry.', 'Meal', 'Medium', 45.0, 4, 1),
('Caesar Salad', 'A fresh salad with Caesar dressing and croutons.', 'Meal', 'Easy', 15.0, 2, 1),
('Grilled Salmon', 'Perfectly grilled salmon with herbs.', 'Meal', 'Easy', 20.0, 2, 1),
('Beef Stroganoff', 'Tender beef in creamy mushroom sauce.', 'Meal', 'Medium', 35.0, 4, 1),
('Vegan Chili', 'A hearty vegan chili loaded with beans and vegetables.', 'Meal', 'Medium', 40.0, 6, 1),
('Apple Pie', 'A traditional apple pie with flaky crust.', 'Dessert', 'Hard', 90.0, 8, 1),
('Margarita Pizza', 'Classic Italian pizza with tomato, mozzarella, and basil.', 'Meal', 'Medium', 30.0, 4, 1),
('Vegetable Soup', 'A comforting bowl of fresh vegetable soup.', 'Meal', 'Easy', 25.0, 4, 1),
('Pancakes', 'Fluffy pancakes with syrup.', 'Breakfast', 'Easy', 20.0, 4, 1),
('Chocolate Chip Cookies', 'Classic cookies with chocolate chips.', 'Dessert', 'Medium', 30.0, 12, 1),
('Spaghetti Carbonara', 'Classic Italian pasta with creamy sauce and bacon.', 'Meal', 'Medium', 25.0, 4, 1),
('French Onion Soup', 'Rich and flavorful soup with caramelized onions.', 'Meal', 'Medium', 50.0, 4, 1),
('Lamb Tagine', 'A slow-cooked Moroccan dish with lamb and spices.', 'Meal', 'Hard', 120.0, 6, 1),
('Tacos', 'Traditional Mexican tacos with beef and salsa.', 'Meal', 'Easy', 30.0, 4, 1),
('Pad Thai', 'Thai stir-fried noodles with a tangy sauce.', 'Meal', 'Medium', 40.0, 4, 1),
('Ratatouille', 'A classic French vegetable stew.', 'Meal', 'Medium', 60.0, 4, 1),
('Lasagna', 'Layered pasta dish with meat and cheese.', 'Meal', 'Hard', 90.0, 8, 1),
('Vegetarian Lasagna', 'A twist on the classic with layers of vegetables and cheese.', 'Meal', 'Hard', 90.0, 8, 1),
('Lentil Soup', 'A hearty and healthy soup made with lentils and vegetables.', 'Meal', 'Easy', 35.0, 4, 1),
('Chicken Tacos', 'Soft taco shells filled with grilled chicken and fresh toppings.', 'Meal', 'Easy', 25.0, 4, 1),
('Shrimp Scampi', 'Garlic butter shrimp served over pasta.', 'Meal', 'Medium', 30.0, 4, 1);




-- Ingredient table
INSERT INTO Ingredient (recipeID, name, quantity, unit) VALUES
(1, 'Spaghetti', '200', 'grams'),
(1, 'Ground Beef', '300', 'grams'),
(1, 'Tomato Sauce', '1', 'cup'),
(2, 'Bell Pepper', '1', 'large'),
(2, 'Carrot', '1', 'medium'),
(2, 'Soy Sauce', '3', 'tablespoons'),
(3, 'Flour', '2', 'cups'),
(3, 'Cocoa Powder', '0.5', 'cup'),
(3, 'Eggs', '3', 'large'),
(4, 'Chicken', '500', 'grams'),
(4, 'Curry Powder', '2', 'tablespoons'),
(4, 'Coconut Milk', '1', 'cup'),
(5, 'Romaine Lettuce', '2', 'heads'),
(5, 'Croutons', '1', 'cup'),
(5, 'Caesar Dressing', '3', 'tablespoons'),
(6, 'Salmon Fillets', '2', 'pieces'),
(6, 'Olive Oil', '2', 'tablespoons'),
(6, 'Lemon Juice', '1', 'tablespoon'),
(7, 'Beef', '500', 'grams'),
(7, 'Mushrooms', '200', 'grams'),
(7, 'Sour Cream', '1', 'cup'),
(8, 'Kidney Beans', '1', 'can'),
(8, 'Tomatoes', '4', 'medium'),
(8, 'Chili Powder', '1', 'tablespoon'),
(9, 'Apples', '5', 'medium'),
(9, 'Sugar', '1', 'cup'),
(9, 'Flour', '2.5', 'cups'),
(10, 'Tomato Sauce', '0.5', 'cup'),
(10, 'Mozzarella', '150', 'grams'),
(10, 'Basil Leaves', '5', 'pieces'),
(11, 'Vegetables', '500', 'grams'),
(11, 'Vegetable Stock', '4', 'cups'),
(11, 'Salt', '1', 'teaspoon'),
(12, 'Flour', '2', 'cups'),
(12, 'Milk', '1.5', 'cups'),
(12, 'Eggs', '2', 'large'),
(13, 'Flour', '2.25', 'cups'),
(13, 'Chocolate Chips', '1', 'cup'),
(13, 'Butter', '1', 'cup'),
(14, 'Pasta', '200', 'grams'),
(14, 'Bacon', '150', 'grams'),
(14, 'Parmesan Cheese', '0.5', 'cup'),
(15, 'Onions', '4', 'large'),
(15, 'Beef Stock', '5', 'cups'),
(15, 'Thyme', '1', 'teaspoon'),
(16, 'Lamb', '1', 'kg'),
(16, 'Cinnamon', '1', 'teaspoon'),
(16, 'Prunes', '200', 'grams'),
(17, 'Ground Beef', '300', 'grams'),
(17, 'Taco Shells', '8', 'pieces'),
(17, 'Cheddar Cheese', '0.5', 'cup'),
(18, 'Rice Noodles', '200', 'grams'),
(18, 'Peanuts', '50', 'grams'),
(18, 'Tamarind Paste', '2', 'tablespoons'),
(19, 'Eggplant', '2', 'large'),
(19, 'Tomato Sauce', '2', 'cups'),
(19, 'Mozzarella', '150', 'grams'),
(20, 'Lasagna Sheets', '12', 'pieces'),
(20, 'Ricotta Cheese', '1.5', 'cups'),
(20, 'Ground Beef', '500', 'grams'),
(21, 'Zucchini', '2', 'medium'),
(21, 'Tomato Sauce', '1', 'cup'),
(21, 'Cheddar Cheese', '0.5', 'cup');



-- Restriction table
INSERT INTO Restriction (restrictionType, recipeID) VALUES
('Gluten-Free', 2),
('Vegetarian', 2),
('Nut-Free', 3),
('Dairy-Free', 4),
('Nut-Free', 5),
('Vegetarian', 11),
('Dairy-Free', 12),
('Nut-Free', 13),
('Gluten-Free', 14),
('Vegetarian', 15),
('Gluten-Free', 16),
('Dairy-Free', 17),
('Vegetarian', 18),
('Nut-Free', 19),
('Gluten-Free', 20),
('Dairy-Free', 21);



-- Rating table
INSERT INTO Rating (userID, recipeID, rate) VALUES
(1, 1, 5),
(2, 2, 4),
(3, 3, 5),
(4, 4, 4),
(5, 5, 5),
(6, 6, 4),
(7, 7, 5),
(8, 8, 4),
(9, 9, 5),
(10, 10, 5),
(11, 11, 4),
(1, 12, 5),
(2, 13, 4),
(3, 14, 5),
(4, 15, 5),
(5, 16, 4),
(6, 17, 5),
(7, 18, 5),
(8, 19, 4),
(9, 20, 5),
(1, 21, 4);


INSERT INTO Instruction (instructionID, instructions, recipeID) VALUES
(1, 'Boil the spaghetti in salted water until al dente; Meanwhile, heat oil in a pan, add ground beef, and cook until browned; Stir in tomato sauce and let simmer for 10 minutes; Combine the sauce with the spaghetti, toss to coat, and serve hot.', 1),
(2, 'Chop all vegetables into uniform bite-sized pieces; Heat oil in a wok over medium heat; Add vegetables and stir-fry for 5 minutes until tender-crisp; Add soy sauce and stir for another 2 minutes; Serve immediately.', 2),
(3, 'Preheat oven to 350°F (175°C); In a mixing bowl, combine flour, sugar, and cocoa powder; Beat eggs in a separate bowl and mix into the dry ingredients; Pour batter into a greased baking pan; Bake for 30 minutes or until a toothpick inserted comes out clean; Let cool before serving.', 3),
(4, 'Cut chicken into bite-sized pieces; Heat oil in a pan and cook chicken until browned; Add curry powder and mix well; Stir in coconut milk and simmer for 20 minutes; Serve over steamed rice.', 4),
(5, 'Chop romaine lettuce into bite-sized pieces; Toss with croutons and Caesar dressing until evenly coated; Sprinkle Parmesan cheese on top and serve chilled.', 5),
(6, 'Brush salmon fillets with olive oil and season with salt and pepper; Preheat grill to medium-high heat and cook salmon for 4-5 minutes per side; Squeeze lemon juice over the cooked salmon and garnish with herbs.', 6),
(7, 'Slice mushrooms and set aside; Heat oil in a skillet, add beef strips, and cook until browned; Stir in mushrooms and cook for another 5 minutes; Add sour cream and simmer until the sauce thickens; Serve over noodles or rice.', 7),
(8, 'In a large pot, combine kidney beans, diced tomatoes, and chili powder; Simmer for 30 minutes on low heat, stirring occasionally; Add salt and pepper to taste; Serve with fresh cilantro as garnish.', 8),
(9, 'Peel, core, and slice apples into thin pieces; Prepare a pie crust and arrange apple slices inside; Sprinkle with sugar and cinnamon; Cover with another crust, seal edges, and bake at 375°F (190°C) for 50 minutes; Let cool before slicing.', 9),
(10, 'Spread tomato sauce on pizza dough; Add mozzarella cheese and fresh basil leaves; Preheat oven to 450°F (230°C) and bake pizza for 12-15 minutes or until the crust is golden brown; Serve hot.', 10),
(11, 'Chop vegetables into small pieces for even cooking; Heat oil in a pot over medium heat; Add vegetables and sauté for 5 minutes; Pour in vegetable stock, season with salt and pepper, and bring to a boil; Simmer for 20 minutes and blend until smooth.', 11),
(12, 'In a large mixing bowl, combine flour, milk, and eggs; Whisk until smooth; Heat a non-stick skillet over medium heat and grease lightly; Pour a small amount of batter, cook until bubbles form, flip, and cook until golden; Serve with syrup or fruit.', 12),
(13, 'Preheat oven to 350°F (175°C); Cream butter and sugar until fluffy; Mix in eggs and vanilla, then gradually add flour and fold in chocolate chips; Drop spoonfuls of dough onto a greased baking sheet and bake for 12 minutes; Cool before serving.', 13),
(14, 'Cook pasta in salted boiling water until al dente; Drain and set aside; In a pan, fry bacon until crispy; Mix cooked pasta with grated Parmesan cheese and crispy bacon; Toss to combine and serve immediately.', 14),
(15, 'Slice onions thinly and caramelize in butter over medium heat for 20 minutes; Add beef stock, thyme, and salt; Bring to a boil, then simmer for 20 minutes; Serve with toasted bread or melted cheese on top.', 15),
(16, 'Marinate lamb pieces with cinnamon and prunes; Heat oil in a large pot and sear the lamb until browned; Add broth or water to cover and bring to a boil; Reduce heat, cover, and simmer for 2 hours until tender.', 16),
(17, 'Cook ground beef in a skillet over medium heat until browned; Add taco seasoning and a splash of water; Simmer for 5 minutes; Warm taco shells in the oven, fill with beef, cheese, lettuce, and salsa; Serve immediately.', 17),
(18, 'Soak rice noodles in warm water for 10 minutes; Heat oil in a wok, add tamarind paste, and toss in noodles; Stir-fry with vegetables and peanuts for 5 minutes; Serve hot.', 18),
(19, 'Preheat oven to 375°F (190°C); Slice eggplant and roast on a baking sheet until softened; In a baking dish, layer roasted eggplant with tomato sauce and mozzarella cheese; Bake for 20 minutes or until bubbly.', 19),
(20, 'Preheat oven to 375°F (190°C); Brown ground beef with onions and garlic; In a baking dish, layer cooked pasta, beef, and cheese; Repeat layers and bake for 30 minutes; Uncover and bake for another 15 minutes.', 20),
(21, 'Preheat oven to 375°F (190°C); Cook pasta until al dente; Brown ground beef with onions and garlic; In a baking dish, layer cooked pasta, beef, and cheese; Repeat layers, then bake for 30 minutes.', 21),
(22, 'For the crust, combine flour, butter, and water, and press into a tart pan; Bake the crust until golden; For the filling, mix fresh fruit and sugar, then fill the crust; Chill before serving.', 22),
(23, 'Mix quinoa with black beans, corn, and diced vegetables; Toss with lime juice and cilantro; Serve as a side or main dish.', 23),
(24, 'Mix oats with milk, honey, and fruit; Let it sit overnight in the fridge; Serve cold for a healthy breakfast.', 24);
